### ISSUE TITLE
Modelo del dominio + Nueva versión de Bootify

### ISSUE THREAD

**Issue by rafarex70** [MasterCloudApps-Projects/your-race#1]
Raquel

**Comment by raquetelio** [comment]
Hay que actualizarlo con la revisión final que estamos haciendo con Bootify

**Comment by raquetelio** [comment]
Crear clase asociada a Race con la responsabilidad de manejar la info asociada al Registration

**Comment by raquetelio** [comment]
Ya están hechos los cambios anteriores en rama https://github.com/MasterCloudApps-Projects/your-race/tree/domain-model-update

**Comment by raquetelio** [comment]
Falta añadir la información relativa al prizing y la subscripción -> Si lo vamos a hacer con Flyway, tendremos que actualizar el Modelo más adelante.

**Comment by raquetelio** [comment]
Pendiente: Actualización con download de Bootify

- Add Constructors (por defecto y no)
- Add cascade to join with application period y Registration
- Add InitializerDataService

++ Cambios rama Rafa: pom.xml (Faker y Actuator, Docker compose)

Revisar que todo ok

**Comment by rafarex70** [comment]
Todo mergeado en main
