### ISSUE TITLE
Faker - Investigation of error

### ISSUE THREAD

**Issue by raquetelio** [MasterCloudApps-Projects/your-race#51]
Investigate why Faker was causing the error that forced to remove it: https://github.com/MasterCloudApps-Projects/your-race/pull/49#issue-1405014277

**Comment by rafarex70** [comment]
Las entidades requieren la base de datos, que es lo que nos generaba errores, podemos implementar faker

**Comment by rafarex70** [comment]
Se implementa a lo largo de los casos de pruebas
