### ISSUE TITLE
Probar Spring reactor para endpoint de registro ByOrder

### ISSUE THREAD

**Issue by raquetelio** [MasterCloudApps-Projects/your-race#76]

**Comment by rafarex70** [comment]
Limitaciones de R2DBC
– No soporta caché (cada petición reconstruye
objetos)
– **No soporta relaciones entre entidades (porque son
bloqueantes)**
https://github.com/spring-projects/spring-data-r2dbc/issues/99#issuecomme
nt-610783285
https://github.com/spring-projects/spring-data-r2dbc/issues/356
https://dzone.com/articles/you-dont-need-hibernate-with-spring-webflux-and-r2

**Comment by rafarex70** [comment]
descartado al no ser aplicable en el esquema actual
